name: Lellimecnar
theme: jekyll-theme-leap-day
title: Lellimecnar
description: Lance Miller
collections:
  costuming:
    title: Costuming
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
